name: benign
version: 0.1.0
author: Arnaud Spiwack
maintainer: arnaud@spiwack.net
github: aspiwack/haskell-benign
copyright: MIT
synopsis: A library for benign effects
description: see README.md.

dependencies:
  - base
  - async
  - containers
  - deepseq
  - stm
  - strict-wrapper

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_benign # substitute name with the package name
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wnoncanonical-monad-instances -Wredundant-constraints

# For executables:
# -threaded -rtsopts -with-rtsopts=-N
