name: benign
version: 0.1.0
author: Arnaud Spiwack
maintainer: arnaud@spiwack.net
github: aspiwack/haskell-benign
copyright: MIT
synopsis: A library for benign effects
description: see README.md.

dependencies:
  - base
  - async
  - containers
  - deepseq
  - stm
  - transformers

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wnoncanonical-monad-instances -Wredundant-constraints

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_benign # substitute name with the package name

executables:
  simple-print:
    source-dirs: examples
    main: SimplePrint.hs
    dependencies:
      - benign
    when:
    - condition: false
      other-modules: Paths_benign # substitute name with the package # name
  # doesn't parse, I'll figure out why later
  # ghc-options: -threaded -rtsopts -with-rtsopts=-N
