name: benign-timestats
version: 0.1.0
author: Arnaud Spiwack
maintainer: arnaud@spiwack.net
github: aspiwack/haskell-benign
copyright: MIT
synopsis: A library for benign effects
description: see README.md.

dependencies:
  - base
  - benign
  - timestats

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wnoncanonical-monad-instances -Wredundant-constraints

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_benign_timestats # substitute name with the package name
